### ISSUE TITLE
Incorrect dependecy between domd and doma with meta-google

### ISSUE THREAD

**Issue by rshym** [xen-troops/moulin#119]
If we use Android with meta-google layer, we create incorrect inter-domain dependency.
The meta-google layer is available only after fetching the DomA. At the same time, this layer must be present when we call conf_domd.
For now, we use fake dependency
```
          domd:
            builder:
              additional_deps:
                # We need some dependency to AOSP artifacts as we are using the "meta-google"
                # layer directly from its source code. Thus DomA should be built before DomD.
                - "../%{DOMA_DIR}/out/target/product/%{ANDROID_DEVICE}/boot.img"
```
But this solution can't guarantee that conf_domd will not be called before DomA is fetched, because this `additional_deps` is used as a dependency for the `domd` target, but not for the `conf_domd` target.

For now, we have two possible solutions.

1) Considering that the `conf_domd` target is created inside yocto-builder, and is the logical component of the `domd` target, we may use `additional_deps` as the dependency for the `conf_domd` instead of `domd`. This will ensure that `conf_domd` waits for the DomA completion.

2) We may add new items `external_layers` for the builder, explicitly stating that some layer is provided from outside, and should be considered as the dependency.
```
          domd:
            builder:
              layers:
                - "../meta-clang"
              external_layers:
                - "../../%{DOMA_DIR}/device/epam/aosp-xenvm-trout/agl_services_build/yocto-layer/meta-google"
```
Such an approach requires that another component declares that the layer is provided by him.
```
  doma:
    builder:
      type: android
      target_images:
        - "out/target/product/%{ANDROID_DEVICE}/boot.img"
        ...
        - "device/epam/aosp-xenvm-trout/agl_services_build/yocto-layer/meta-google" 
```
