### ISSUE TITLE
rouge: create partition from specific rootfs folder

### ISSUE THREAD

**Issue by al1img** [xen-troops/moulin#39]
We need the functionality which yocto wic plugin does: it can pack the specific folder into a separate partition. It is required in the following use cases: RO rootfs + RW /var or/and RW /home. We should have a possibility to add /var /home files into separate partition.

**Comment by rshym** [comment]
The solution is on review https://github.com/xen-troops/moulin/pull/60

**Comment by rshym** [comment]
Required functionality was merged as #60.
You need to use `items` instead of `files`.
Using `items` you may specify folders to be used as content for partition. Symlinks are preserved inside directories for ext4 partitions.

**Comment by lorc** [comment]
@al1img are you satisfied with the solution? Can we close the issue?

**Comment by al1img** [comment]
Not fully. I can't set file permissions. I would like to control `root_owner` and `-d root-directory` options of `mkfs` command.

**Comment by lorc** [comment]
I see... Do you have an idea how this can be describe at YAML level? E.g. what format should work for you? In the most generic case it should be something like this:

```
items_ext:
  - source: "/local/path"
    destination: "/path/on/image"
    permissions: "rwxrw-r--" (or maybe just 0642?)
    owner: "root"
    group: "root"
  - source: "/other/local/path"
    destination: "/oher/path/on/image"
    permissions: "rw------"
    owner: "root"
    group: "root"
```
Problem is that it is quite mouthful. And can grow very fast. And `mkfs.ext4` command does not support such features, so we need to find another solution.
