### ISSUE TITLE
rouge: it is impossible to put files into some folder on ext4 partition

### ISSUE THREAD

**Issue by al1img** [xen-troops/moulin#40]
Example;
```yaml
    partitions:
      boot_a:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "/my_folder/my_file": "local/file"
```
