### ISSUE TITLE
Incorrect handling of multiple revisions for same repo

### ISSUE THREAD

**Issue by rshym** [xen-troops/moulin#85]
We may have an erroneous situation when two different revisions are specified for the same repo, used in two different components. For example:

```
  doma:
    sources:
      - type: git
        url: https://github.com/xen-troops/meta-example.git
        rev: "ABCDEF"

  domu:
    sources:
      - type: git
        url: https://github.com/xen-troops/meta-example.git
        rev: "branch_A"
```
If we run `ninja fetch-domu` we will have meta-example fetched and checked out to `ABCDEF` instead of the expected `branch_A`.
Seems like the checkout rule is created for the first revision met in yaml-file.

So, the main issue is that this erroneous declaration is handled silently.
Looks like the best way is to fail the generation of `build.ninja` in case of conflicting revisions.
